spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyzer
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      jdbc.time_zone: UTC
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: none
    show-sql: false
  sql.init.mode: always

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      springframework.cloud.netflix.eureka: INFO
      apache.kafka: WARN

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    hub-event-topic: telemetry.hubs.v1
    sensor-snapshot-topic: telemetry.snapshots.v1
